### ISSUE TITLE
Strict standard issue

### ISSUE THREAD

**Issue by jasin755** [h4kuna/gettext-latte#17]
Strict standards
h4kuna\BasePresenter and h4kuna\Gettext\InjectTranslator define the same property ($lang) in the composition of h4kuna\BasePresenter. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed

![snimek obrazovky 2015-03-17 v 14 34 47](https://cloud.githubusercontent.com/assets/10629189/6688338/d148ca88-ccb2-11e4-868a-53ad35cfc5be.png)

**Comment by h4kuna** [comment]
Let use code above comment or below comment not both.

**Comment by h4kuna** [comment]
It means for PHP<5.4 or 5.4+

**Comment by jasin755** [comment]
PHP 5.6. I know that this is an example, but for some reason is loading. If I manually delete the folder examples, so it's OK.

**Comment by h4kuna** [comment]
Are you using robotloader for vendor directory?

**Comment by jasin755** [comment]
No, RobotLoader is set only on the app folder.
