### ISSUE TITLE
GettextSetup a implements \Nette\Localization\ITranslator

### ISSUE THREAD

**Issue by ViPErCZ** [h4kuna/gettext-latte#19]
Toto chybí v této třídě, což je škoda.

**Comment by h4kuna** [comment]
Ze své podstaty fungování gettextu, interface není potřeba. Toto je jen makro pro latte podporující gettext + rozšíření přes extension. Jinými slovy bude fungovat bez ITranslatoru. Funguje dobře na linuxu, na windows s tím mám potíže.

**Comment by h4kuna** [comment]
Proč to potřebuješ? Hoď po mě kus kódu.

**Comment by h4kuna** [comment]
Obalování řetězců gettext funkcí, funguje zároveň jako identifikátor pro xgettext který parsuje texty ze zdrojáků, pokud by jsi použil
```php
$form->addText('foo', 'Jméno');
```
Tak ti to nenajde proto je potřeba to použít 
```php
$form->addText('foo', _('Jméno')); // zároveň funguje jako překladová funkce
```
kde pak není potřeba ITranslator.

**Comment by ViPErCZ** [comment]
Třeba kvůli tomuto: http://doc.nette.org/cs/2.3/localization#toc-preklad-sablon
Konkrétně pak: $this->template->setTranslator($translator);
Pokud někde předávám závyslost obecného typu ITranslator (bavíme se o Nette), pak při přechodu na tvojí knihovnu mám celkem problém a musel bych měnit type hint v setterech, kde toto předávám.

**Comment by h4kuna** [comment]
Makro ktere je

**Comment by h4kuna** [comment]
Tak udělám větev kde bude implementován interface a ty teď potřebuješ? Na větev se přepneš v composeru a dáš mi nějaký feedback.

**Comment by h4kuna** [comment]
Pro:
- kompatibilita a možnost rychlého přepnutí překladače

Proti:
- podle mě to bude způsobovat větší wtf

**Comment by ViPErCZ** [comment]
No já ti udělal pull request. Nyní jsem si u sebe upravil zdroj z composeru (což je čuňačina).

**Comment by ViPErCZ** [comment]
To proti jsem úplně nepochopil?

**Comment by h4kuna** [comment]
Jen aby lidi nepsali že to nastavujou
```php
$form->setTranslator(...)
```
A ono to nepřekládá. to je taková ochrana, že to nastavit nejde a funguje to jinak.

**Comment by h4kuna** [comment]
Metoda translate by teoreticky mohla vracet jen řetězec a nic s ním nedělat?

**Comment by ViPErCZ** [comment]
Má tohle někde nějakou dokumnetaci? Protože teď mi to je tak trochu jasné. I když nyní nechápu proč nefunguje oboje. Nette dle dokumentace právě $form->setTranslator(...) podporuje. Chápu, že toto mělo jakýmsi způsobem věc pojmou trochu jináč. Každopádně toto beru jako nadstavbu a setnout to do šablony jako OK postup.
Btw nemusí jít jen o $form->setTranslator(...) ale také o $template->setTranslator(...). Do template to bylo také zakázané?

**Comment by h4kuna** [comment]
Dokumentace je v README.md na hlavní stránce. Rád ji rozšířím ale v tuhle chvíli mám pocit že tam je vše důležité.

Je to pojmuté jinak, protože nativní gettext nemůže být hnán přes nějakou abstrakci protože tím ztratí tu druhou funkcionalitu kdy jedním zápisem to funguje jako identifikátor pro nalezení textů do slovníku a za druhé jako překladová funkce.

**Comment by h4kuna** [comment]
Pokud chceš můžem si zavolat na skype a probrat to. Piloter77

**Comment by ViPErCZ** [comment]
Tak jsem se k tomu zase vrátil... teď mě to třeba omezilo v používání hrachova nextras gridu, kde má taky nad gridem public metodu setTranslator a ta má taky typehint ITranslator. Takže v tomto případě další přiohýbání dvou věcí pro Nette. Asi bych se spíše řídil konvencí Nette a předdefinovaným interfacem ITranslator, na který se v minulosti či budoucnosti budou lidé spoléhat. A pak je potíž, když si až časem vzpomenou, že by použili tvoji extension :-)

**Comment by h4kuna** [comment]
ITranslator je [implementovaný](https://github.com/h4kuna/gettext-latte/blob/master/src/GettextSetup.php#L14), ale podle mě to způsobí více potíží než užitku aby gettext fungoval správně musíš do funkce gettext dát statický texty a to rozšíření ITranslator nezajistí. Respektive překládat to bude ale nedude fungovat xgettext, který čte překlady pro slovník.

gettext je rychlý a je potřeba znát jak funguje jinak bude lepší použít symfony translator.

**Comment by ViPErCZ** [comment]
Aha... já v composeru nastavil číselnou verzi namísto dev-masteru a tak to tam nemám.
Asi to koukám vyžaduje jistý znalosti namísto toho, abych řekněme jednoduše překládal :-)
To že jsou nějaké důvody samozřejmě chápu a věřím, že jsou velmi dobré proč jsi to tak udělal. Nevím jak tom je to řešitelné, aby se zachovala kompatibilita právě s ostatními konvenceme, které spoléhají na ITranslator. Jestli udělat do tvé extension nějakou factory a object co mi v případě nejvyšší nutnosti takový ITranslator objekt vyrobí. Netuším... Na Symfony translator se mrknu, díky.
