### ISSUE TITLE
Windows 64bit

### ISSUE THREAD

**Issue by camohub** [h4kuna/gettext-latte#25]
Zdravím, 
prosím ťa mám pred sebou projekt, ktorý používa tvoju knižnicu na preklad. Ale nech robím čo chcem mne to neprekladá. Niekde som čítal, že to má nejaký problém s 64bit Windowsami. 
Mám v presentery úplne primitívny kód 

    		Debugger::barDump(_('Testujeme translator'), 'translation');

 ale dostanem len pôvodný text. Žiadny error nič. Keď si vydumpujem translator vyzerá, že je nastavený správne. V PoEdit upravím .po súbor a vygenerujem .mo, ale nemá to žiadny efekt. Tak teda neviem, či mám hľadať ešte problém u seba, alebo je to fakt mimo mňa.

**Comment by h4kuna** [comment]
Nebudu ti lhát mě se to taky na windows nikdy nepovedlo rozchodit, ale jelikož 4 roky už mám ubuntu tak mě to moc netrápilo a servry jsou taky linuxí. Pokud chceš doplněk použít vyzkoušej ho na servru. Nebo je tu Kdyby\Translator.

**Comment by camohub** [comment]
Projekt je už rozbehnutý , takže kdyby tam už bez obetí nedostanem. Tak dúfam, že na servri to bude fungovať. Díky za rýchlu reakciu.

**Comment by h4kuna** [comment]
Si to nejprve vyzkoušej, než to nasadíš, nicméně na linuxu to určitě funguje.

**Comment by camohub** [comment]
Zdravím znova. chcem sa s pýtať či by si mi vedel povedať, kde podľa teba dochádza k tomu problému. V čom to podľa teba je, prípadne na ktorý súbor sa mám zamerať, keby som sa teoreticky chcel na to pozrieť.
Keby bol napr. chybne vygenerovaný .mo súbor tak by to v Tracy niečo vypísalo, alebo by to potichu preplo na default? K chybe musí dôjsť niekde pri spracovaní toho súboru.

**Comment by h4kuna** [comment]
Chyba je podle mě že windows neumí pracovat s locale, respektive on to nějak umí ale zatím jsem nepřišel na to jak. Všechno se nastavuje v [loadDictionary](../blob/master/src/GettextSetup.php#L242)

Možná že se něco už zlepšilo [stackoverflow](http://stackoverflow.com/questions/1473207/php-gettext-on-windows) a ještě jednou [stackoverflow](http://stackoverflow.com/questions/12356987/gettext-on-windows-7-doesnt-translate)

**Comment by h4kuna** [comment]
Nějaký pokrok?

**Comment by camohub** [comment]
Pokrok žiadny, zatiaľ nemám čas a dúfam, že na Linuxe to funguje.

**Comment by h4kuna** [comment]
Mimochodem nemám to testovaný pro nette 2.4.

**Comment by camohub** [comment]
A neskúšal si to porovnať s inými nette knižnicami? Nikto iný to neriešil?


S pozdravom

*Vladimír Čamaj*

2016-11-23 7:45 GMT+01:00 Milan Matějček <notifications@github.com>:

**Comment by h4kuna** [comment]
Nikdo jiný neřeší gettext v jeho pravé podstatě :) většinou využívají jen po nebo mo soubory ale nikoliv ten gettext engine, který je implementovaný v php.
