### ISSUE TITLE
Makro {_$control->getValue()}

### ISSUE THREAD

**Issue by xpackal5** [h4kuna/gettext-latte#26]
Zdravím a děkuji za užitečný addon. Rád bych ho používal společně s Ublaboo\Datagrid, ale nefungue makro {_$control->getNejakaHodnota()}. Hlásí to LatteException wrong macro. Je nějaká cesta jak to vyřešít?
Díky Milan

**Comment by h4kuna** [comment]
Momentálně nevím.
To generuje komponenta Datagrid? Nebo jsi to tam napsal ty? Nemá náhodou ta komponenta nějaký vlastní translator? 

Mimochodem translator nebude dobře fungovat pokud obsahuje dynamické texty v proměnných.

**Comment by xpackal5** [comment]
Ten datagrid bere cokoliv, co implementuje ITranslator. Takže může mít svůj. Když ho ale použiju, tak je funkce _ z datagridu v konfliktu s _ z gettextu. Datagrid není můj je z Componette (jde o Ublaboo/Datagrid). Chybu generuje šablona datagridu a generuje ji na {_$nejakyObjekt->metoda()}. No nevadí jen jsem se chtěl zeptat. Nějak se s tím poperu. Díky

**Comment by h4kuna** [comment]
Makro {_Foo} je v nette 2.4 odebráno. A mělo by se to psát přes filter {Foo|translate}. Tak jestli nemáš zastaralou knihovnu toho datagridu? Ikdyž doplněk  makra s podtržítkama doinstaluje... Nejsem si úplně jist že by to měla být chyba doplňku. Protože LatteException nikde nevyhazuji.
