### ISSUE TITLE
Probaly you have not instaled locale support on your machine. Let's try command: $ locale -a

### ISSUE THREAD

**Issue by camohub** [h4kuna/gettext-latte#27]
Zdravím,
nevieš prosím ťa čo by toto mohlo byť za error:
"Probaly you have not instaled locale support on your machine. Let's try command: $ locale -a, or h4kuna\Gettext\GettextSetup::showAvailableLanguages()"

Na lokale mi to funguje, ale na online servery vyhodí toto. Pritom, jazyky sk, en, de fungujú normálne, len cz mi vyhodí túto chybu. Skopíroval som celý lang/cz adresár takže by to malo byť ok. 
Čo by to ešte mohlo byť? Za každý nápad díky.

**Comment by camohub** [comment]
Tak toto som trochu nepochopil. Skúsil som zmeniť parameter v neone na **cz: 'cs_CZ.utf8'**
````
    	langs:
		sk: 'sk_SK.utf8'
		en: 'en_US.utf8'
		**cz: 'cs_CZ.utf8'**
		de: 'de_DE.utf8'
````
Takže na locale s Windows 10 mi funguje **cz: 'cz_CZ.utf8'** ale servery **cz: 'cs_CZ.utf8'**??? Má to tak byť?

**Comment by camohub** [comment]
No tak aby toho nebolo málo, skúsil som zmeniť na locale cz_CZ.utf8 na cs_CZ.utf8 a zdá sa že to funguje.

**Comment by h4kuna** [comment]
Chování na windows nemám odskoušené. Takže pokud na Windows reaguje na cz_CZ.utf8 možné to je.
