### ISSUE TITLE
Latte Compiller nefunguje s Nette 2.4

### ISSUE THREAD

**Issue by xpackal5** [h4kuna/gettext-latte#28]
Zdravím, v Nette 2.4. nefunguje latte compiler

Fatal Error

Call to a member function getHttpResponse() on null search►

Source file

File: .../src/Bridges/ApplicationLatte/TemplateFactory.php:106

 96:            $template->user = $this->user;
 97:            $template->baseUri = $template->baseUrl = $this->httpRequest ? rtrim($this->httpRequest->getUrl()->getBaseUrl(), '/') : NULL;
 98:            $template->basePath = preg_replace('#https?://[^/]+#A', '', $template->baseUrl);
 99:            $template->flashes = [];
100:            if ($control) {
101:                $template->control = $control;
102:                $template->presenter = $presenter;
103:                $latte->addProvider('uiControl', $control);
104:                $latte->addProvider('uiPresenter', $presenter);
105:                $latte->addProvider('snippetBridge', new Nette\Bridges\ApplicationLatte\SnippetBridge($control));
106:                $nonce = preg_match('#\s\'nonce-([\w+/]+=*)\'#', $presenter->getHttpResponse()->getHeader('Content-Security-Policy'), $m) ? $m[1] : NULL;
107:                $latte->addProvider('uiNonce', $nonce);
108:            }
109:            $latte->addProvider('cacheStorage', $this->cacheStorage);
110:

**Comment by h4kuna** [comment]
Ok mrknu na to.

**Comment by h4kuna** [comment]
Testni master.
