### ISSUE TITLE
Issue with translations on FreeBSD

### ISSUE THREAD

**Issue by ghost** [h4kuna/gettext-latte#29]
Hi, I have this site with two language mutations (SK/EN) running on **FreeBSD** system. 
Translations in localhost (on Mac) work, but not on FreeBSD.

**Specs:**

Nette: **2.2.7**
PHP: **5.6.30**
gettext-latte: **1.3.3**

```
langs:
    sk: 'sk_SK.UTF-8'
    en: 'en_US.UTF-8'
```

output of [phpinfo](https://cl.ly/o8Fs/phpinfo.html)

Can you help me with this? Thanks

**Comment by h4kuna** [comment]
What server return on command?
```
$ locale -a
```
Server must return supported languages.

**Comment by Kaliver88** [comment]
Server return those languages: 

```
array [
  ...
  19 => "en_US.UTF-8"
  ...
  51 => "sk_SK.UTF-8"
]
```
_output of `barDump($this->translator->showAvailableLanguages());` from tracy_

**Comment by h4kuna** [comment]
Everything looks like fine. If you don't see exception with message 'Probaly you have not instaled locale support on your machine....'

Disctionaries are on server with right path?
