### ISSUE TITLE
master vrze

### ISSUE THREAD

**Issue by JStika** [h4kuna/gettext-latte#30]
Pres composer dostanu verzi 1.3.3 a mam chybu:
User Deprecated
Replace deprecated Nette\Object with trait Nette\SmartObject in D:\Www\www.slovago2.sk\vendor\h4kuna\gettext-latte\src\Dictionary.php:17

Jak se dostanu k master verzi?
Natte 2.4.4, php 7.1.9.

Dekuji za odpoved.

**Comment by h4kuna** [comment]
Zkuste dev-master, jinak doplněk je nevyvíjený. Tudíž zestárne v čase.

**Comment by h4kuna** [comment]
Pokud ho budete chtít zaktualizovat tak změny sloučím. Ale já na vývoj momentálně nemám kapacity.

**Comment by JStika** [comment]
Dekuji, dev-master pomohlo. Ale, kdy dam do BasePresenter

    public function injectTranslator(\h4kuna\GettextSetup $translator) {
        $this->translator = $translator;
    }
zase dostavam toto:

Nette\DI\ServiceCreationException

Service 'application.1' (type of App\Presenters\Error4xxPresenter): Class h4kuna\GettextSetup needed by $translator in App\Presenters\BasePresenter::injectTranslator() not found. Check type hint and 'use' statements. search►

**Comment by h4kuna** [comment]
To je chyba v dokumentaci, ona třída h4kuna\GettextSetup neexistuje, má tam být h4kuna\Gettext\GettextSetup.

**Comment by h4kuna** [comment]
Dokumentaci jsem opravil a vydal jsem verzi 1.3.4

**Comment by JStika** [comment]
Veelmi mooooc dekuji za pomoc.
