### ISSUE TITLE
Vicejazycny web

### ISSUE THREAD

**Issue by JStika** [h4kuna/gettext-latte#31]
Ahoj,

jak muzu predavat zvolene locale (sk,en,.....),  treba kvuli moment.js?
Ted mam vice vetvi v confi s koncovkou Locale.

**Comment by h4kuna** [comment]
No... koukám že to není možné vytáhnout. Pokud můžeš, udělej fork a připrav PR.

**Comment by JStika** [comment]
Na to az tak Nette neznam dobre....

**Comment by h4kuna** [comment]
Na to momentálně namám kapacitu abych to udělal. Navíc to nesouvisí s nette, ale s touhle knihovnou.

**Comment by JStika** [comment]
To je to, co u Nette a jeho komunity nesnasim (s porovnamim s Symfony, Laravel), dobry napad a podpora skoro nulova. Pro Nette 3 (i kdyz je betta), starsi veci nefunguji, a ty dobre veci pro Nette 2.4 umiraji, nebo jsou uplne mrtve.

**Comment by h4kuna** [comment]
Ta úprava nebude složitá, tak proč to neuděláš, když to potřebuješ? Pořád to pro tebe bude méně času něž psát něco jiného nebo migrovat jinam. Samozřejmě můžeš přejít na symfony/translate.

**Comment by h4kuna** [comment]
Navíc jsi byl na to loni v září upozorněn, že doplně zestárne. https://github.com/h4kuna/gettext-latte/issues/30

**Comment by JStika** [comment]
Vyresil jsem si to "nejak".
Ale na co se delaji rozsireni, aby setrily cas, ne?

Je jsem presel na  php z c#, nestacim se divit, jak to, ci ono je problematicke.

**Comment by h4kuna** [comment]
Funguje to asi takto: Já jsem si napsal rozšíření pro nette, který jsem potřeboval a šetřilo mi čas a bylo znovupoužitelné už od nette 2.0, poskytnul jsem ho zdarma, ale nikde není psaný že to zdarma budu udržovat ikdyž to nepotřebuju, pro mě momentálně nemá hodnotu, musí se zapojit i ostatní, udělám code review, sloučím to hned jak to půjde, ale nemohu to všechno udržovat. Je tu více [projektů](https://github.com/h4kuna/library). Mám jinou práci a rodinu, už nejsem student. 

Nebo za 500,- ti tam doplním co chceš a za 1500,- upgrade na nette3.

**Comment by JStika** [comment]
ok, nechto tak.
